### ISSUE TITLE
random number generation app

### ISSUE THREAD

**Issue by floswald** [ScPoEcon/ScPoEconometrics#29]
* we need to introduce the idea of a data generating process
* we are workign towards the concept of *model*
* for that we need to understand how to draw observations from a process
* the idea that every tiem you draw, you get a different sample of points
* ultimately this will infomr the discussion about standard errors in regression models
* we've already done "as you increase N, the sample approximates better the pdf", so need something else

### app ideas

* i want them to repeatedly draw from a process and see always differen realizations.
* let's go with the regression y = a + bx + u
* assume u ~ N(0,sigma), fix a and b
* have a button "redraw"
* scatter plot of y ~ x
* N < 20
* could do something with a joint normal distribution instead of regression
* i like the idea of just observign the changing scatter plot rather than looking at a histogram.
* other ideas welcome - let's discuss here!

**Comment by vviers** [comment]
I'm thinking we could also have the last few set of drawn points progressively fade away so that we can visually compare the new draw with the last one
this would probably be fairly easy with plotly

I also remember seeing an app in which we did basically the same thing, except we kept adding the regression line to the model (it was a way to illustrate the notion of bootstrap, but I guess it still makes sense in a context where we compute the S.E. and CI analytically because it illustrate the variability of the estimated regression line)

**Comment by floswald** [comment]
i like the idea of the fading points.
