### ISSUE TITLE
change regapp squared errors

### ISSUE THREAD

**Issue by floswald** [ScPoEcon/ScPoEconometrics#30]
currently you do

```R
    rect(xleft = x, ybottom = y,
         xright = x + abs(errors), ytop = y + errors, density = -1,
         col = rgb(red = 0, green = 1, blue = 0, alpha = 0.1), border = NA)
```

I find it nicer like this:

```R
    rect(xleft = x, ybottom = y,
         xright = x + abs(errors), ytop = y - errors, density = -1,
         col = rgb(red = 0, green = 1, blue = 0, alpha = 0.1), border = NA)
```

(just swap the sign in front of `errors` for `y`.

this will have rectangles point downwards for points above the line, and vice versa.

**Comment by vviers** [comment]
Done. Just noticed an 'issue' with the dummy regression:

The x-y aspect ratio is set to .25 (because otherwise we wouldn't see much of what's happening on the x-axis) ==> so the error squares appear as rectangles in the plot...

Probably not a big deal (and, if anything, a good homework question for students to think about), but I'll leave it to your call.
